title: Your awesome title
description: An awesome description for your new site
baseurl: ""
url: ""
permalink: pretty

copyright: false
indexing: false

exclude:
  - demo/
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
