title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: "https://jekyll-nagymaros.netlify.app"
repo: "https://github.com/piazzai/jekyll-nagymaros"

permalink: pretty
indexing: true
copyright: Place Holder

exclude:
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
