title: Your awesome title
description: An awesome description for your new site.
baseurl: ""
url: ""

permalink: pretty
indexing: false
copyright: false

exclude:
  - jekyll-nagymaros.gemspec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
