title: Nagymaros
description: Jekyll theme for a conference website
baseurl: /dev
url: "https://github.piazzai.io/jekyll-nagymaros"

copyright: Place Holder

exclude:
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
