title: Nagymaros
description: Jekyll theme for a conference website
author: Place Holder
baseurl: ""
url: "https://github.piazzai.io/jekyll-nagymaros"

exclude:
  - jekyll-nagymaros.gemspec
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap