title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: "https://jekyll-nagymaros.netlify.app"
permalink: pretty

indexing: true
copyright: false

exclude:
  - jekyll-nagymaros.gemspec

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
