title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: "https://jekyll-nagymaros.netlify.app"
permalink: pretty

indexing: true
copyright: Place Holder

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
