title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: "https://jekyll-nagymaros.netlify.app"

theme: jekyll-nagymaros

indexing: true
copyright: Place Holder

exclude:
  - LICENSE
  - README.md
