title: Nagymaros
description: Jekyll theme for a conference website
baseurl: ""
url: "https://jekyll-nagymaros.netlify.app"

theme: jekyll-nagymaros

copyright: Place Holder
indexing: true

exclude:
  - LICENSE
  - README.md
